#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
ok() { echo -e "${GREEN}ok${NC} $1"; }
warn() { echo -e "${YELLOW}!${NC} $1"; }
fail() { echo -e "${RED}x${NC} $1"; exit 1; }

echo
echo "  codex-app-custom-models setup"
echo

command -v node >/dev/null 2>&1 || fail "Node.js not found. Install from https://nodejs.org"
ok "Node.js $(node --version)"
command -v npm >/dev/null 2>&1 || fail "npm not found"

if ! command -v opencodex >/dev/null 2>&1; then
  warn "Installing @bitkyc08/opencodex"
  npm i -g @bitkyc08/opencodex
fi
ok "opencodex $(opencodex --version 2>/dev/null || echo installed)"

# Apply bundled patches (re-run after every "opencodex update")
if [ -d "$ROOT/patches" ]; then
  bash "$ROOT/scripts/apply-patches.sh" || warn "Patch step failed; see patches/README"
fi

CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
OPENCODEX_HOME="${OPENCODEX_HOME:-$HOME/.opencodex}"
mkdir -p "$OPENCODEX_HOME" "$CODEX_HOME"

# Never overwrite a live config that already has keys unless user agrees
if [ -f "$OPENCODEX_HOME/config.json" ]; then
  read -r -p "~/.opencodex/config.json exists. Replace with template? (y/N): " overwrite
  if [ "$overwrite" = "y" ] || [ "$overwrite" = "Y" ]; then
    cp "$ROOT/configs/opencodex/config.json" "$OPENCODEX_HOME/config.json"
    ok "Replaced opencodex config template"
  else
    warn "Kept existing opencodex config"
  fi
else
  cp "$ROOT/configs/opencodex/config.json" "$OPENCODEX_HOME/config.json"
  ok "Installed opencodex config template"
fi
chmod 600 "$OPENCODEX_HOME/config.json"

cat > "$CODEX_HOME/opencodex.config.toml" << TOML
# Generated by codex-app-custom-models setup. Safe to regenerate.
openai_base_url = "http://127.0.0.1:10100/v1"
TOML
ok "Wrote $CODEX_HOME/opencodex.config.toml"

# Merge proxy pointer into config.toml if present, without touching projects
if [ -f "$CODEX_HOME/config.toml" ]; then
  if ! grep -q 'openai_base_url' "$CODEX_HOME/config.toml"; then
    printf '\nopenai_base_url = "http://127.0.0.1:10100/v1"\n' >> "$CODEX_HOME/config.toml"
    ok "Appended openai_base_url to existing config.toml"
  else
    ok "config.toml already points at a proxy"
  fi
fi

put_key() {
  local placeholder="$1"
  local value="$2"
  if [ -n "$value" ]; then
    python3 - "$OPENCODEX_HOME/config.json" "$placeholder" "$value" << 'PY'
import json, sys
path, placeholder, value = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(path).read().replace(placeholder, value)
open(path, "w").write(text)
PY
    chmod 600 "$OPENCODEX_HOME/config.json"
    return 0
  fi
  return 1
}

echo
echo "API keys (paste is hidden; skip with Enter)"
read -r -p "MiMo key (tp-sk...): " -s mimo_key; echo
put_key "YOUR_MIMO_API_KEY_HERE" "$mimo_key" && ok "MiMo key stored" || warn "MiMo skipped"

read -r -p "DeepSeek key (sk-...): " -s ds_key; echo
put_key "YOUR_DEEPSEEK_API_KEY_HERE" "$ds_key" && ok "DeepSeek key stored" || warn "DeepSeek skipped (or use: opencodex login deepseek)"

read -r -p "GLM / Z.AI key: " -s glm_key; echo
put_key "YOUR_GLM_API_KEY_HERE" "$glm_key" && ok "GLM key stored" || warn "GLM skipped"

read -r -p "Log in to Grok (xAI OAuth) now? (y/N): " grok
if [ "$grok" = "y" ] || [ "$grok" = "Y" ]; then
  opencodex login xai || warn "Run later: opencodex login xai"
fi

echo
bash "$ROOT/scripts/validate.sh" || true
opencodex restart || warn "Run: opencodex restart"
sleep 1
bash "$ROOT/scripts/health-check.sh" || true

echo
echo "Quit Codex fully, reopen, pick a model."
echo "Keys stay in $OPENCODEX_HOME/config.json — do not commit that file."
